breadcrumb_separator: fa-angle-right
scroll_to_top_display: 1
scroll_to_top_text: Top
color_scheme: red
animations_state: 1
slideout_background_color: 'region--light-typography region--dark-background'
slideout_side: left
slideout_touch_swipe: 1
header_top_highlighted_layout_container: container
header_top_highlighted_background_color: 'region--light-typography region--dark-background'
header_top_highlighted_animation_effect: fadeIn
header_top_layout_container: container
header_top_background_color: 'region--light-typography region--dark-background'
header_top_animation_effect: fadeIn
header_layout_container: container-fluid
fixed_header: 1
content_top_layout_container: container
content_top_background_color: 'region--dark-typography region--white-background'
content_top_animation_effect: fadeIn
content_top_highlighted_layout_container: container
content_top_highlighted_separator: region--no-separator
content_top_highlighted_background_color: 'region--dark-typography region--gray-background'
content_top_highlighted_animation_effect: fadeIn
media_background_layout_container: container-fluid
media_background_separator: region--no-separator
media_background_background_color: 'region--dark-typography region--white-background'
media_background_animation_effect: no-animation
main_content_separator: region--no-separator
main_content_animation_effect: fadeIn
sidebar_first_animation_effect: fadeInLeft
sidebar_second_animation_effect: fadeInRight
content_bottom_layout_container: container-fluid
content_bottom_separator: region--no-separator
content_bottom_background_color: 'region--light-typography region--black-background'
content_bottom_animation_effect: fadeIn
featured_top_layout_container: container
featured_top_separator: region--no-separator
featured_top_background_color: 'region--dark-typography region--white-background'
featured_top_animation_effect: fadeInDown
featured_layout_container: container-fluid
featured_separator: region--separator-border-top
featured_background_color: 'region--dark-typography region--white-background'
featured_animation_effect: fadeInDown
featured_bottom_layout_container: container
featured_bottom_separator: region--no-separator
featured_bottom_background_color: 'region--dark-typography region--gray-background'
featured_bottom_animation_effect: fadeInLeft
sub_featured_layout_container: container-fluid
sub_featured_separator: region--no-separator
sub_featured_background_color: 'region--dark-typography region--white-background'
sub_featured_animation_effect: fadeIn
highlighted_top_layout_container: container
highlighted_top_separator: region--no-separator
highlighted_top_background_color: 'region--dark-typography region--white-background'
highlighted_top_animation_effect: fadeIn
highlighted_layout_container: container-fluid
highlighted_separator: region--no-separator
highlighted_background_color: 'region--dark-typography region--gray-background'
highlighted_animation_effect: fadeIn
footer_top_layout_container: container
footer_top_separator: region--no-separator
footer_top_background_color: 'region--dark-typography region--white-background'
footer_top_animation_effect: fadeInUp
footer_layout_container: container
footer_separator: region--no-separator
footer_background_color: 'region--light-typography region--dark-background'
footer_animation_effect: fadeIn
footer_bottom_layout_container: container
footer_bottom_separator: region--no-separator
footer_bottom_background_color: 'region--light-typography region--dark-background'
subfooter_layout_container: container
subfooter_separator: region--no-separator
subfooter_background_color: 'region--light-typography region--dark-background'
reading_time: 0
post_progress: 1
layout_mode: wide
headings_font_family: hff-08
paragraph_font_family: pff-06
sitename_font_family: sff-08
slogan_font_family: slff-08
rs_slideshow_fullscreen_effect: random
rs_slideshow_fullscreen_effect_time: '10'
rs_slideshow_fullscreen_navigation_style: titles_carousel
rs_slideshow_fullscreen_bullets_position: right
rs_slideshow_fullscreen_touch_swipe: 1
transparent_header_state: 1
transparent_header_opacity: '90'
rs_slideshow_fullwidth_effect: random
rs_slideshow_fullwidth_effect_time: '10'
rs_slideshow_fullwidth_initial_height: '650'
rs_slideshow_fullwidth_navigation_style: bullets
rs_slideshow_fullwidth_bullets_position: center
rs_slideshow_fullwidth_touch_swipe: 1
rs_slideshow_boxedwidth_effect: random
rs_slideshow_boxedwidth_effect_time: '10'
rs_slideshow_boxedwidth_initial_height: '650'
rs_slideshow_boxedwidth_navigation_style: titles_carousel
rs_slideshow_boxedwidth_bullets_position: center
rs_slideshow_boxedwidth_touch_swipe: 1
rs_slideshow_internal_effect: fade
rs_slideshow_internal_effect_time: '10'
rs_slideshow_internal_initial_height: '380'
rs_slideshow_internal_navigation_style: bullets
rs_slideshow_internal_banner_bullets_position: center
rs_slideshow_internal_touch_swipe: 1
rs_slideshow_caption_opacity: '70'
in_page_slider_effect: slide
owl_products_autoplay: 1
owl_products_effect_time: '5'
owl_related_nodes_autoplay: 0
owl_related_nodes_effect_time: '5'
owl_brands_autoplay: 1
owl_brands_effect_time: '5'
owl_collections_autoplay: 0
owl_collections_effect_time: '5'
parallax_and_video_bg_state: none
parallax_and_video_bg_opacity: '0'
isotope_layout_mode: masonry
isotope_filters_text: All
google_maps_key: AIzaSyDyL-4KyWw_3hp-0jmZLGcJ3zMWkkJ44VI
_core:
  default_config_hash: p5HuXijH-Ng2bT3vZ8XvQVIrEQ0MjNuD51YJPD7SmUk
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: themes/custom/showcaseplus/hm-logo.png
favicon:
  use_default: false
  path: themes/custom/showcaseplus/favicon.png
  mimetype: image/png
font_title: ''
rs_slideshow_internal_bullets_position: left
video_bg_state: none
video_bg_opacity: ''
scroll_to_top_icon: fa-angle-up
scroll_to_top_region: footer-to-top-enabled
slideout_blocks_paddings: 0
slideout_region_paddings: 0
header_top_highlighted_blocks_paddings: 0
header_top_highlighted_region_paddings: 0
header_top_blocks_paddings: 0
header_top_region_paddings: 0
header_blocks_paddings: 0
header_region_paddings: 0
content_top_blocks_paddings: 0
content_top_region_paddings: 0
content_top_highlighted_blocks_paddings: 0
content_top_highlighted_region_paddings: 0
media_background_blocks_paddings: 0
media_background_region_paddings: 1
main_content_blocks_paddings: 0
main_content_region_paddings: 0
sidebar_first_blocks_paddings: 0
sidebar_first_region_paddings: 0
sidebar_second_blocks_paddings: 0
sidebar_second_region_paddings: 0
content_bottom_blocks_paddings: 0
content_bottom_region_paddings: 1
featured_top_blocks_paddings: 0
featured_top_region_paddings: 0
featured_blocks_paddings: 0
featured_region_paddings: 0
featured_bottom_blocks_paddings: 0
featured_bottom_region_paddings: 0
sub_featured_blocks_paddings: 0
sub_featured_region_paddings: 0
highlighted_top_blocks_paddings: 0
highlighted_top_region_paddings: 0
highlighted_blocks_paddings: 1
highlighted_region_paddings: 1
footer_top_blocks_paddings: 0
footer_top_region_paddings: 0
footer_blocks_paddings: 0
footer_region_paddings: 0
footer_bottom_blocks_paddings: 0
footer_bottom_region_paddings: 0
subfooter_blocks_paddings: 0
subfooter_region_paddings: 0
owl_articles_autoplay: 1
owl_articles_effect_time: '5'
banner_layout_container: container-fluid
banner_background_color: 'region--dark-typography region--gray-background'
banner_blocks_paddings: 1
banner_region_paddings: 1
owl_testimonials_autoplay: 1
owl_testimonials_effect_time: '5'
headings_wide_spacing: 1
header_background_color: 'region--dark-typography region--gray-background'
page_container_border: 0
